### ISSUE TITLE
Gromacs tests failing on Vega when tried with `srun`, `mpirun` and `pmix`

### ISSUE THREAD

**Issue by satishskamath** [EESSI/test-suite#72] opened 2023-07-18 09:47 UTC
Both `srun`, `mpirun` hang when `SLURM_MPI_TYPE=pmix`  .

**Comment by casparvl** [comment] 2023-07-18 09:54
To add here: the failure seems to be a hang of `mpirun` until it finally times out. I reproduced this with an allocation created through `salloc`. Calling `mpirun` when `SLURM_MPI_TYPE=pmix` is set will cause `mpirun` to hang indefinitely on the login node: no processes are ever spawned in the allocation. When `SLURM_MPI_TYPE=pmix` was _not_ set, there were no issues.

One thing to note is that _unsetting_ `SLUMR_MPI_TYPE` after a hang did _not_ resolve the issue. I guess once it's messed up, it's messed up well...

**Comment by casparvl** [comment] 2023-07-31 09:06
Not sure what was wrong before exactly, as we didn't log much in this issue. But, the daily runs show they are working again:

```
[ ESC[32m      OKESC[0m ] (5/8) GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=1_node %module_name=GROMACS/2020.1-foss-2020a-Python-3.8.2 /695f354c @vega:cpu+default
P: perf: 347.017 ns/day (r:0, l:None, u:None)
[ ESC[32m      OKESC[0m ] (6/8) GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=1_node %module_name=GROMACS/2020.4-foss-2020a-Python-3.8.2 /a108fe65 @vega:cpu+default
P: perf: 362.405 ns/day (r:0, l:None, u:None)
[ ESC[32m      OKESC[0m ] (7/8) GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=2_nodes %module_name=GROMACS/2020.4-foss-2020a-Python-3.8.2 /c3790f2a @vega:cpu+default
P: perf: 371.077 ns/day (r:0, l:None, u:None)
[ ESC[32m      OKESC[0m ] (8/8) GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=2_nodes %module_name=GROMACS/2020.1-foss-2020a-Python-3.8.2 /5535abba @vega:cpu+default
P: perf: 372.467 ns/day (r:0, l:None, u:None)
[----------] all spawned checks have finished

[ ESC[31m FAILED ESC[0m ] Ran 8/8 test case(s) from 8 check(s) (4 failure(s), 0 skipped, 0 aborted)
[==========] Finished on Thu Jul 27 00:01:45 2023
```
(4 failing tests where TensorFlow tests, but nothing to be worried about in the context of this issue). I'll close this for now.

**Closed by casparvl** 2023-07-31 09:06 UTC
